# Generated by Django 4.1.4 on 2022-12-29 20:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("product_types", "0001_initial"),
        ("product_models", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=150)),
                ("price", models.DecimalField(decimal_places=2, max_digits=5)),
                (
                    "color",
                    models.CharField(
                        choices=[("R", "Red"), ("B", "Blue"), ("G", "Gray")],
                        max_length=50,
                    ),
                ),
                ("description", models.TextField()),
                ("stock", models.IntegerField()),
                ("brand", models.CharField(max_length=150)),
                ("img1", models.ImageField(upload_to="images/")),
                ("img2", models.ImageField(upload_to="images/")),
                ("img3", models.ImageField(upload_to="images/")),
                ("img4", models.ImageField(upload_to="images/")),
                ("img5", models.ImageField(upload_to="images/")),
                ("slug", models.SlugField()),
                (
                    "model_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="product_models.brandmodel",
                    ),
                ),
                (
                    "type_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="product_types.type",
                    ),
                ),
            ],
        ),
    ]
